services:
  bot:
    image: chithien0909/download-bot:latest
    restart: always
    env_file:
      - ../.env
    environment:
      SERVER_PORT: "${SERVER_PORT:-:8080}"
      DB_PATH: "/data/db/bot.db"
      DOWNLOAD_DIR: "/data/downloads"
      CACHE_DIR: "/data/cache"
    ports:
      - "8080:8080"
    volumes:
      - ./data/downloads:/data/downloads
      - ./data/db:/data/db
      - ./data/cache:/data/cache
